### ISSUE TITLE
throwing Server is busy error.

### ISSUE THREAD

**Issue by mack1290** [splunk/splunk-javascript-logging#31]
Description: 
{ Error: Server is busy at Request._callback (/usr/src/app/node_modules/splunk-logging/splunklogger.js:484:35) at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22) at Request.emit (events.js:182:13) at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10) at Request.emit (events.js:182:13) at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12) at Object.onceWrapper (events.js:273:13) at IncomingMessage.emit (events.js:187:15) at endReadableNT (_stream_readable.js:1085:12) at process._tickCallback (internal/process/next_tick.js:63:19) code: 9 }

**Comment by mack1290** [comment]
my findings: i think _body.text is undefined due to which it is going into hung state.

if (!splunkError && _body && _body.code && _body.code.toString() !== "0") {
                    splunkError = new Error(_body.text);
                    splunkError.code = _body.code;
                }

**Comment by shakeelmohamed** [comment]
@mack1290 nice find, we're open to a PR but not sure if we'll be able to repro this one easily ourselves.
